edit_mode = "vi"
path = ["/home/sam/.cargo/bin", "/home/sam/.local/bin", "/usr/local/bin", "/usr/bin", "/bin", "/usr/local/sbin", "/usr/lib/jvm/default/bin", "/usr/bin/site_perl", "/usr/bin/vendor_perl", "/usr/bin/core_perl", "/var/lib/snapd/snap/bin", "/home/sam/go/bin", "/home/sam/bin", "/home/sam/.emacs.d/bin"]

[env]
COLORFGBG = "default;default"
DBUS_SESSION_BUS_ADDRESS = "unix:path=/run/user/1000/bus"
DESKTOP_STARTUP_ID = "i3/i3-sensible-terminal/4517-1-desk_TIME28909"
DISPLAY = ":0"
GTK_MODULES = "canberra-gtk-module"
HOME = "/home/sam"
I3SOCK = "/run/user/1000/i3/ipc-socket.4517"
INVOCATION_ID = "b9573e73b35a4728a20539adcbe001fb"
JOURNAL_STREAM = "9:22857"
LOGNAME = "sam"
MAIL = "/var/spool/mail/sam"
PWD = "/home/sam"
SHELL = "/bin/bash"
SHLVL = "1"
TERM = "alacritty"
USER = "sam"
WINDOWID = "16777226"
WINDOWPATH = "1"
XDG_RUNTIME_DIR = "/run/user/1000"
XDG_SEAT = "seat0"
XDG_SESSION_CLASS = "user"
XDG_SESSION_ID = "1"
XDG_SESSION_TYPE = "tty"
XDG_VTNR = "1"
EDITOR = "emacs"
